version: '3.8'
services:

  postgres:
    image: postgres:15
    container_name: pg-marketplace
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rmq-marketplace
    ports:
      - '5672:5672'
      - '15672:15672'
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '1025:1025'   # SMTP
      - '8025:8025'   # Web UI



volumes:
  pgdata:
